#pragma once


#include "event_type.hpp"
#include <string>


namespace andromeda
{
    /// @brief Defines the interface for an event.
    ///
    /// An event represents an occurrence generated by the application,
    /// windowing system, or input devices. Events can be categorized,
    /// identified by type, and marked as handled after processing.
    class IEvent
    {
    public:
        /// @brief Virtual destructor.
        virtual ~IEvent() = default;

        /// @brief Checks whether the event has been handled.
        ///
        /// @return `true` if the event has been handled; otherwise, `false`.
        virtual bool is_handled() const = 0;

        /// @brief Marks the event as handled or unhandled.
        ///
        /// @param handled `true` to mark the event as handled; otherwise, `false`.
        virtual void set_handled(bool handled) = 0;

        /// @brief Checks whether the event belongs to a category.
        ///
        /// @param category Event category to test.
        /// @return `true` if the event belongs to the specified category;
        /// otherwise, `false`.
        virtual bool is_in_category(EventCategory category) const = 0;

        /// @brief Retrieves the event category flags.
        ///
        /// @return Bitmask of `EventCategory` flags.
        virtual int get_category_flags() const = 0;

        /// @brief Retrieves the event name.
        ///
        /// @return Human-readable event name.
        virtual std::string get_name() const = 0;

        /// @brief Converts the event to a string representation.
        ///
        /// @return String describing the event.
        virtual std::string to_string() const = 0;

        /// @brief Retrieves the event type.
        ///
        /// @return The event type.
        virtual EventType get_event_type() const = 0;
    };
}
