#ifndef API__WINDOW__EVENTS__I_KEY_EVENTS_HPP
#define API__WINDOW__EVENTS__I_KEY_EVENTS_HPP


#include "i_event.hpp"
#include "../mouse_and_key_codes/key_codes.hpp"


namespace andromeda
{
    /// @brief Defines the base interface for keyboard events.
    ///
    /// Provides access to the keyboard key associated with the event.
    class IKeyEvent
        : public virtual IEvent
    {
    public:
        /// @brief Virtual destructor.
        virtual ~IKeyEvent() = default;

        /// @brief Retrieves the key associated with the event.
        ///
        /// @return Keyboard key code.
        virtual KeyCode get_key_code() const = 0;
    };

    /// @brief Defines the interface for a key pressed event.
    ///
    /// Generated when a keyboard key is pressed. Repeated key press events may
    /// also be generated while a key is held down.
    class IKeyPressedEvent
        : public virtual IKeyEvent
    {
    public:
        /// @brief Virtual destructor.
        virtual ~IKeyPressedEvent() = default;

        /// @brief Checks whether this event was generated by key repetition.
        ///
        /// @return `true` if the event is an auto-repeat; otherwise, `false`.
        virtual bool is_repeat() const = 0;
    };

    /// @brief Defines the interface for a key released event.
    ///
    /// Generated when a keyboard key is released.
    class IKeyReleasedEvent
        : public virtual IKeyEvent
    {
    public:
        /// @brief Virtual destructor.
        virtual ~IKeyReleasedEvent() = default;
    };

    /// @brief Defines the interface for a key typed event.
    ///
    /// Generated when character input is received from the keyboard.
    class IKeyTypedEvent
        : public virtual IKeyEvent
    {
    public:
        /// @brief Virtual destructor.
        virtual ~IKeyTypedEvent() = default;
    };
}


#endif // API__WINDOW__EVENTS__I_KEY_EVENTS_HPP