#pragma once


#include "event_base.hpp"
#include "andromeda/window/events/event_type.hpp"
#include "andromeda/window/mouse_and_key_codes/key_codes.hpp"
#include "andromeda/window/events/i_key_events.hpp"
#include "pch.hpp"


namespace andromeda::window
{
    /// @brief Base class for keyboard-related events.
    ///
    /// Stores the key associated with the event and provides common keyboard
    /// event category information.
    class KeyEvent
        : public EventBase
        , public virtual IKeyEvent
    {
    public:
        /// @brief Constructs a keyboard event.
        ///
        /// @param keycode Key associated with the event.
        explicit KeyEvent(KeyCode keycode);

        /// @brief Destroys the keyboard event.
        ~KeyEvent() override;

        /// @brief Checks whether the event belongs to a category.
        ///
        /// @param category Event category to test.
        /// @return `true` if the event belongs to the category; otherwise, `false`.
        bool is_in_category(EventCategory category) const override;

        /// @brief Retrieves the event category flags.
        ///
        /// @return Bitmask representing the event categories.
        int get_category_flags() const override;

        /// @brief Retrieves the key associated with the event.
        ///
        /// @return Keyboard key code.
        KeyCode get_key_code() const override;

    protected:
        /// @brief Keyboard key associated with the event.
        KeyCode m_key_code;
    };

    /// @brief Event emitted when a keyboard key is pressed.
    class KeyPressedEvent
        : public KeyEvent
        , public virtual IKeyPressedEvent
    {
    public:
        /// @brief Constructs a key press event.
        ///
        /// @param keycode Key that was pressed.
        /// @param is_repeat Indicates whether the event was generated by key repeat.
        KeyPressedEvent(KeyCode keycode, bool is_repeat);

        /// @brief Destroys the key press event.
        ~KeyPressedEvent() override;

        /// @brief Checks whether the key press is a repeat event.
        ///
        /// @return `true` if generated by key repeat; otherwise, `false`.
        bool is_repeat() const override;

        /// @brief Retrieves the event type.
        ///
        /// @return Event type identifier.
        EventType get_event_type() const override;

        /// @brief Retrieves the event name.
        ///
        /// @return Event name.
        std::string get_name() const override;

        /// @brief Converts the event to a human-readable string.
        ///
        /// @return String representation of the event.
        std::string to_string() const override;

    private:
        /// @brief Indicates whether the key press is a repeat.
        bool m_is_repeat;
    };

    /// @brief Event emitted when a keyboard key is released.
    class KeyReleasedEvent
        : public KeyEvent
        , public virtual IKeyReleasedEvent
    {
    public:
        /// @brief Constructs a key release event.
        ///
        /// @param keycode Key that was released.
        explicit KeyReleasedEvent(KeyCode keycode);

        /// @brief Destroys the key release event.
        ~KeyReleasedEvent() override;

        /// @brief Retrieves the event type.
        ///
        /// @return Event type identifier.
        EventType get_event_type() const override;

        /// @brief Retrieves the event name.
        ///
        /// @return Event name.
        std::string get_name() const override;

        /// @brief Converts the event to a human-readable string.
        ///
        /// @return String representation of the event.
        std::string to_string() const override;
    };

    /// @brief Event emitted when a character is typed.
    ///
    /// Represents text input after keyboard layout and input processing.
    class KeyTypedEvent
        : public KeyEvent
        , public virtual IKeyTypedEvent
    {
    public:
        /// @brief Constructs a key typed event.
        ///
        /// @param keycode Typed key code.
        explicit KeyTypedEvent(KeyCode keycode);

        /// @brief Destroys the key typed event.
        ~KeyTypedEvent() override;

        /// @brief Retrieves the event type.
        ///
        /// @return Event type identifier.
        EventType get_event_type() const override;

        /// @brief Retrieves the event name.
        ///
        /// @return Event name.
        std::string get_name() const override;

        /// @brief Converts the event to a human-readable string.
        ///
        /// @return String representation of the event.
        std::string to_string() const override;
    };
}
