#ifndef PHYSICAL_PROPERTIES__TRANSFORMATION_TYPES__HPP
#define PHYSICAL_PROPERTIES__TRANSFORMATION_TYPES__HPP


namespace Andromeda::PhysicalProperties
{
	enum class TransformationType
	{
		TRANSLATE,
		ROTATE,
		SCALE,
		ALL
	};
}


#endif // PHYSICAL_PROPERTIES__TRANSFORMATION_TYPES__HPP